[package]
name = "dtls_server"
version = "0.1.0"
authors = ["jmendoza"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
udp-dtls = "0.1.0"
openssl = "0.10.29"
